/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import ec.edu.ups.conexion.Conexion;
import ec.edu.ups.conexion.SentenciasCRUD;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Catalogo_Vehiculo;

/**
 *
 * @author israelchuchuca
 */
public class InterfazCatalogo extends javax.swing.JFrame {

    
    DefaultTableModel dmt;
    Object[] o =new Object [7];
    /**
     * Creates new form InterfazCatalogo
     */
    public InterfazCatalogo() {
        initComponents();
        tblcatalogo.addMouseListener(new MouseAdapter() {
            
            
            public void mousePressed(MouseEvent Mouse_evt){
                JTable table = (JTable ) Mouse_evt.getSource();
                Point point= Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if(Mouse_evt.getClickCount()==2){
                    
                    JOptionPane.showMessageDialog(null, "El vehiculo con placa : "+tblcatalogo.getValueAt(tblcatalogo.getSelectedRow(), 3).toString()+ "  fue seleccionado para alquiler");
                }
                
                
            
            }
            });
        
       
       
      
        dmt=(DefaultTableModel) tblcatalogo.getModel();
        
        /**
     *   o[0]="cate_nombre";
        o[1]="cate__precio_dia_controlado";
        o[2]="cate__precio_adicional_km";
        o[3]="veh_placa";
        o[4]="veh_color";
        o[5]="mod_nombre";
        o[6]="sdsd";
        dmt.addRow(o);
     */
        // TODO add your handling code here:
        
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcatalogo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLugarEntrega = new javax.swing.JTextField();
        txtHoraEntrega = new javax.swing.JTextField();
        txtFechaFecha = new javax.swing.JTextField();
        comboTarifa = new javax.swing.JComboBox<>();
        txtLugarDevolucion = new javax.swing.JTextField();
        txtHoraDevolucion = new javax.swing.JTextField();
        txtFechaDevolucion = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        btnContrato = new javax.swing.JButton();
        catalogo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THRIFTTY-RENTAR");
        setMinimumSize(new java.awt.Dimension(1300, 450));
        getContentPane().setLayout(null);

        tblcatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "categoria", "tarifa kilometraje controlado", "kilometraje adicional", "placa vehiculo", "color ", "modelo", "marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcatalogo.setGridColor(new java.awt.Color(120, 120, 120));
        jScrollPane1.setViewportView(tblcatalogo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 0, 1030, 400);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entrega");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Devolucion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 120, 22);

        txtLugarEntrega.setText("Lugar");
        getContentPane().add(txtLugarEntrega);
        txtLugarEntrega.setBounds(30, 50, 70, 20);

        txtHoraEntrega.setText("Hora");
        getContentPane().add(txtHoraEntrega);
        txtHoraEntrega.setBounds(110, 50, 60, 20);

        txtFechaFecha.setText("Fecha");
        getContentPane().add(txtFechaFecha);
        txtFechaFecha.setBounds(30, 90, 50, 20);

        comboTarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccione]", "Controlado", "Ilimitado" }));
        comboTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTarifaActionPerformed(evt);
            }
        });
        getContentPane().add(comboTarifa);
        comboTarifa.setBounds(90, 90, 100, 20);

        txtLugarDevolucion.setText("Lugar");
        txtLugarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarDevolucionActionPerformed(evt);
            }
        });
        getContentPane().add(txtLugarDevolucion);
        txtLugarDevolucion.setBounds(30, 160, 70, 20);

        txtHoraDevolucion.setText("Hora");
        getContentPane().add(txtHoraDevolucion);
        txtHoraDevolucion.setBounds(110, 160, 60, 20);

        txtFechaDevolucion.setText("Fecha");
        getContentPane().add(txtFechaDevolucion);
        txtFechaDevolucion.setBounds(30, 200, 70, 20);

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(30, 300, 80, 23);

        btnContrato.setText("Realizar Contrato");
        getContentPane().add(btnContrato);
        btnContrato.setBounds(120, 300, 117, 23);

        catalogo.setText("catalogo");
        catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoActionPerformed(evt);
            }
        });
        getContentPane().add(catalogo);
        catalogo.setBounds(83, 240, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/Fondo categoria.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, -20, 280, 420);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, -30, 452, 402);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(240, 100, 150, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLugarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarDevolucionActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        InterfazEmpleado interfazEmpleado = new InterfazEmpleado();
        interfazEmpleado.setVisible(true);
        
      
    }//GEN-LAST:event_btnInicioActionPerformed

    private void comboTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTarifaActionPerformed

    private void catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoActionPerformed
        
        Conexion con = new Conexion();
        con.setUrl("jdbc:oracle:thin:@localhost:1521:orcl");
        con.setUsername("DBCARENTAL");
        con.setPassword("dbcarrental");
        con.Conectar();
        
        
        if (con.getConexion() != null){
            System.out.println("Base de datos conectada");
        
            
        }
        
        
              try{
            psentencia = con.getConexion().prepareStatement("   select c.cate_nombre,c.cate__precio_dia_controlado,c.cate__precio_adicional_km,v.veh_placa,v.veh_color,mo.mod_nombre,m.mar_nombre\n" +
"   from ren_categorias c , ren_vehiculos v, ren_marcas m ,ren_modelos mo\n" +
"   where c.cate_id=v.ren_categorias_cate_id and m.mar_id=mo.ren_marcas_mar_id and v.ren_modelos_mod_id=mo.mod_id");
     
            resultado = psentencia.executeQuery();
            
            //Se presenta el resultado
            while (resultado.next()){
        o[0]=resultado.getString(1);
        o[1]=resultado.getDouble(2);
        o[2]=resultado.getDouble(3);
        o[3]=resultado.getString(4);
        o[4]=resultado.getString(5);
        o[5]=resultado.getString(6);
        o[6]=resultado.getString(7);
        
        dmt.addRow(o);
            }
            con.CerrarConexion();
        }
        catch(SQLException e){
            e.printStackTrace();
        }    
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
      
    
      

    }//GEN-LAST:event_catalogoActionPerformed
  
    public void sentencia(Conexion con) {
        
    }
    
  
   


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContrato;
    private javax.swing.JButton btnInicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton catalogo;
    private javax.swing.JComboBox<String> comboTarifa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblcatalogo;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaFecha;
    private javax.swing.JTextField txtHoraDevolucion;
    private javax.swing.JTextField txtHoraEntrega;
    private javax.swing.JTextField txtLugarDevolucion;
    private javax.swing.JTextField txtLugarEntrega;
    // End of variables declaration//GEN-END:variables

   private ResultSet resultado = null;
   private PreparedStatement psentencia = null;

    public ResultSet getResultado() {
        return resultado;
    }

    public void setResultado(ResultSet resultado) {
        this.resultado = resultado;
    }

    public PreparedStatement getPsentencia() {
        return psentencia;
    }

    public void setPsentencia(PreparedStatement psentencia) {
        this.psentencia = psentencia;
    }
   
   
}