/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ISRA ALVA
 */
public class InterfazRegistroEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistroEmpleado
     */
    public InterfazRegistroEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXTENOMBRE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXTEAPELLIDO = new javax.swing.JTextField();
        TXTECEDULA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXTEUSUARIO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTEPASSWORD = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 33, 42, 14);
        getContentPane().add(TXTENOMBRE);
        TXTENOMBRE.setBounds(70, 30, 86, 20);

        jLabel2.setText("APELLIDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 77, 48, 14);

        TXTEAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEAPELLIDOActionPerformed(evt);
            }
        });
        getContentPane().add(TXTEAPELLIDO);
        TXTEAPELLIDO.setBounds(68, 74, 88, 20);

        TXTECEDULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTECEDULAActionPerformed(evt);
            }
        });
        getContentPane().add(TXTECEDULA);
        TXTECEDULA.setBounds(273, 30, 68, 20);

        jLabel3.setText("CEDULA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(192, 33, 39, 14);
        getContentPane().add(TXTEUSUARIO);
        TXTEUSUARIO.setBounds(273, 74, 68, 20);

        jLabel4.setText("USUARIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(185, 77, 46, 14);

        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(185, 130, 57, 14);

        TXTEPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTEPASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(TXTEPASSWORD);
        TXTEPASSWORD.setBounds(273, 130, 68, 20);

        jButton1.setText("Listo");
        jButton1.setMaximumSize(new java.awt.Dimension(200, 300));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 300));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(273, 182, 55, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car-rental.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTEPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEPASSWORDActionPerformed

    private void TXTEAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTEAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTEAPELLIDOActionPerformed

    private void TXTECEDULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTECEDULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTECEDULAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRegistroEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazRegistroEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTEAPELLIDO;
    private javax.swing.JTextField TXTECEDULA;
    private javax.swing.JTextField TXTENOMBRE;
    private javax.swing.JTextField TXTEPASSWORD;
    private javax.swing.JTextField TXTEUSUARIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
