/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author israelchuchuca
 */
public class InterfazCatalogo extends javax.swing.JFrame {

    
    DefaultTableModel dmt;
    Object[] o =new Object [1];
    /**
     * Creates new form InterfazCatalogo
     */
    public InterfazCatalogo() {
        initComponents();
        dmt=(DefaultTableModel) tblcatalogo.getModel();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcatalogo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLugarEntrega = new javax.swing.JTextField();
        txtHoraEntrega = new javax.swing.JTextField();
        txtFechaFecha = new javax.swing.JTextField();
        comboTarifa = new javax.swing.JComboBox<>();
        txtLugarDevolucion = new javax.swing.JTextField();
        txtHoraDevolucion = new javax.swing.JTextField();
        txtFechaDevolucion = new javax.swing.JTextField();
        btnInicio = new javax.swing.JButton();
        btnContrato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THRIFTTY-RENTAR");
        setMinimumSize(new java.awt.Dimension(630, 370));
        getContentPane().setLayout(null);

        tblcatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "categoria", "tarifa kilometraje controlado", "kilometraje adicional", "placa vehiculo", "color ", "modelo", "marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblcatalogo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(243, 0, 320, 340);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entrega");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Devolucion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 120, 22);

        txtLugarEntrega.setText("Lugar");
        getContentPane().add(txtLugarEntrega);
        txtLugarEntrega.setBounds(30, 50, 70, 20);

        txtHoraEntrega.setText("Hora");
        getContentPane().add(txtHoraEntrega);
        txtHoraEntrega.setBounds(110, 50, 60, 20);

        txtFechaFecha.setText("Fecha");
        getContentPane().add(txtFechaFecha);
        txtFechaFecha.setBounds(30, 90, 50, 20);

        comboTarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccione]", "Controlado", "Ilimitado" }));
        comboTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTarifaActionPerformed(evt);
            }
        });
        getContentPane().add(comboTarifa);
        comboTarifa.setBounds(90, 90, 100, 20);

        txtLugarDevolucion.setText("Lugar");
        txtLugarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarDevolucionActionPerformed(evt);
            }
        });
        getContentPane().add(txtLugarDevolucion);
        txtLugarDevolucion.setBounds(30, 160, 70, 20);

        txtHoraDevolucion.setText("Hora");
        getContentPane().add(txtHoraDevolucion);
        txtHoraDevolucion.setBounds(110, 160, 60, 20);

        txtFechaDevolucion.setText("Fecha");
        getContentPane().add(txtFechaDevolucion);
        txtFechaDevolucion.setBounds(30, 200, 70, 20);

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(30, 300, 80, 23);

        btnContrato.setText("Realizar Contrato");
        getContentPane().add(btnContrato);
        btnContrato.setBounds(120, 300, 117, 23);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 230, 73, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagen/Fondo categoria.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 340);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, -30, 452, 321);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(240, 100, 150, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLugarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarDevolucionActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        InterfazEmpleado interfazEmpleado = new InterfazEmpleado();
        interfazEmpleado.setVisible(true);
        
      
    }//GEN-LAST:event_btnInicioActionPerformed

    private void comboTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTarifaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        o[1]=txtFechaDevolucion.getText();
        dmt.addRow(o);
    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContrato;
    private javax.swing.JButton btnInicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboTarifa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblcatalogo;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaFecha;
    private javax.swing.JTextField txtHoraDevolucion;
    private javax.swing.JTextField txtHoraEntrega;
    private javax.swing.JTextField txtLugarDevolucion;
    private javax.swing.JTextField txtLugarEntrega;
    // End of variables declaration//GEN-END:variables

    


}